[package]
name = "bugwd"
version = "0.1.0"
authors = ["Matt Brubeck <mbrubeck@limpet.net>"]
edition = "2018"

[dependencies.rouille]
version = "3.0"
default-features = false

[dependencies]
mnemonic = "1.0"
